name: Continuous Deployment
env:
  APP_PATH: "/var/apps/api/joedev-api"
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SMARTDEALSHOST }}
          username: ${{ secrets.SMARTDEALSUSERNAME }}
          password: ${{ secrets.SMARTDEALSPASSWORD }}
          port: ${{ secrets.SMARTDEALSPORT }}
          script: |
            cd ${{ env.APP_PATH }}
            git add .
            git pull origin dev